package com.edaochina.shopping.api.dao.user;

import com.edaochina.shopping.domain.dto.user.CheckInvitatCodeDTO;
import com.edaochina.shopping.domain.dto.user.CommuntyPartnerDTO;
import com.edaochina.shopping.domain.entity.user.SysCommunityPartner;
import com.edaochina.shopping.domain.vo.user.SysCommunityPartnerVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

@Repository
public interface SysCommunityPartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    int insert(SysCommunityPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    int insertSelective(SysCommunityPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    SysCommunityPartner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysCommunityPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_community_partner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCommunityPartner record);

    SysCommunityPartner selectByNameAndPhone(SysCommunityPartner sysCommunityPartner);

    List<SysCommunityPartnerVo> querySysCommunityPartners(CommuntyPartnerDTO dto);

    int addBalance(@Param("partenerId") String partenerId, @Param("agentPrice") BigDecimal agentPrice);

    SysCommunityPartner queryByAccount(String account);

    SysCommunityPartner queryByLiveCode(String liveCode);

    /**
     * 查询
     *
     * @param account 账号
     * @param status  状态
     * @return 列表
     */
    int queryByAccountAndStatusCount(@Param("account") String account, @Param("status") int status);

    Integer checkInvitatCodeAndCounty(@Param("invitatCode") String invitatCode, @Param("countyId") String countyId);

    SysCommunityPartner queryByInvitatCode(String invitatCode);

    int updateBalanceMoney(@Param("userId") String userId, @Param("money") double v);

    SysCommunityPartner checkInvitatCode(CheckInvitatCodeDTO dto);
}