package com.edaochina.shopping.api.dao.trade;

import com.edaochina.shopping.domain.entity.trade.PaymentRecord;

import java.util.List;

public interface PaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    int insert(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    int insertSelective(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    PaymentRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentRecord record);

    List<PaymentRecord> queryUnkown();
}