package com.edaochina.shopping.api.dao.trade;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.edaochina.shopping.domain.dto.trade.SysShareGoodsProfitDTO;
import com.edaochina.shopping.domain.entity.trade.TradeDetailShareProfit;
import com.edaochina.shopping.domain.vo.trade.SysShareProfitVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Mapper
@Repository
public interface TradeDetailShareProfitMapper extends BaseMapper<TradeDetailShareProfit> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    int insert(TradeDetailShareProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    int insertSelective(TradeDetailShareProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    TradeDetailShareProfit selectByPrimaryKey(Integer id);

    BigDecimal promotionPriceSum(@Param("userType") int userType, @Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeDetailShareProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeDetailShareProfit record);

    List<SysShareProfitVo> getShareProfitList(SysShareGoodsProfitDTO dto);

    BigDecimal getShareByRoleAndUserId(@Param("roleId") Integer roleId, @Param("userId") String userId, @Param("beginTime") LocalDateTime beginTime, @Param("endTime") LocalDateTime endTime);
}