package com.edaochina.shopping.domain.entity.trade;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TradeDetailShareProfit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.id
     *
     * @mbggenerated
     */
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.share_profit
     *
     * @mbggenerated
     */
    private BigDecimal shareProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.to_account_money
     *
     * @mbggenerated
     */
    private BigDecimal toAccountMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_detail_share_profit.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.id
     *
     * @return the value of trade_detail_share_profit.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.id
     *
     * @param id the value for trade_detail_share_profit.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.order_id
     *
     * @return the value of trade_detail_share_profit.order_id
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.order_id
     *
     * @param orderId the value for trade_detail_share_profit.order_id
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.user_type
     *
     * @return the value of trade_detail_share_profit.user_type
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.user_type
     *
     * @param userType the value for trade_detail_share_profit.user_type
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.user_id
     *
     * @return the value of trade_detail_share_profit.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.user_id
     *
     * @param userId the value for trade_detail_share_profit.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.share_profit
     *
     * @return the value of trade_detail_share_profit.share_profit
     * @mbggenerated
     */
    public BigDecimal getShareProfit() {
        return shareProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.share_profit
     *
     * @param shareProfit the value for trade_detail_share_profit.share_profit
     * @mbggenerated
     */
    public void setShareProfit(BigDecimal shareProfit) {
        this.shareProfit = shareProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.to_account_money
     *
     * @return the value of trade_detail_share_profit.to_account_money
     * @mbggenerated
     */
    public BigDecimal getToAccountMoney() {
        return toAccountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.to_account_money
     *
     * @param toAccountMoney the value for trade_detail_share_profit.to_account_money
     * @mbggenerated
     */
    public void setToAccountMoney(BigDecimal toAccountMoney) {
        this.toAccountMoney = toAccountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.create_time
     *
     * @return the value of trade_detail_share_profit.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.create_time
     *
     * @param createTime the value for trade_detail_share_profit.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_detail_share_profit.update_time
     *
     * @return the value of trade_detail_share_profit.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_detail_share_profit.update_time
     *
     * @param updateTime the value for trade_detail_share_profit.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeDetailShareProfit other = (TradeDetailShareProfit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
                && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getShareProfit() == null ? other.getShareProfit() == null : this.getShareProfit().equals(other.getShareProfit()))
                && (this.getToAccountMoney() == null ? other.getToAccountMoney() == null : this.getToAccountMoney().equals(other.getToAccountMoney()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getShareProfit() == null) ? 0 : getShareProfit().hashCode());
        result = prime * result + ((getToAccountMoney() == null) ? 0 : getToAccountMoney().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_detail_share_profit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", userType=").append(userType);
        sb.append(", userId=").append(userId);
        sb.append(", shareProfit=").append(shareProfit);
        sb.append(", toAccountMoney=").append(toAccountMoney);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}