package com.edaochina.shopping.domain.entity.trade;

import java.io.Serializable;
import java.util.Date;

public class WithdrawalSpecialUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.user_type
     *
     * @mbggenerated
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.auto_bank_rate
     *
     * @mbggenerated
     */
    private Long autoBankRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.to_bank_rate
     *
     * @mbggenerated
     */
    private Long toBankRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdrawal_special_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdrawal_special_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.id
     *
     * @return the value of withdrawal_special_user.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.id
     *
     * @param id the value for withdrawal_special_user.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.user_type
     *
     * @return the value of withdrawal_special_user.user_type
     * @mbggenerated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.user_type
     *
     * @param userType the value for withdrawal_special_user.user_type
     * @mbggenerated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.user_id
     *
     * @return the value of withdrawal_special_user.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.user_id
     *
     * @param userId the value for withdrawal_special_user.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.auto_bank_rate
     *
     * @return the value of withdrawal_special_user.auto_bank_rate
     * @mbggenerated
     */
    public Long getAutoBankRate() {
        return autoBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.auto_bank_rate
     *
     * @param autoBankRate the value for withdrawal_special_user.auto_bank_rate
     * @mbggenerated
     */
    public void setAutoBankRate(Long autoBankRate) {
        this.autoBankRate = autoBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.to_bank_rate
     *
     * @return the value of withdrawal_special_user.to_bank_rate
     * @mbggenerated
     */
    public Long getToBankRate() {
        return toBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.to_bank_rate
     *
     * @param toBankRate the value for withdrawal_special_user.to_bank_rate
     * @mbggenerated
     */
    public void setToBankRate(Long toBankRate) {
        this.toBankRate = toBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.create_time
     *
     * @return the value of withdrawal_special_user.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.create_time
     *
     * @param createTime the value for withdrawal_special_user.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdrawal_special_user.update_time
     *
     * @return the value of withdrawal_special_user.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdrawal_special_user.update_time
     *
     * @param updateTime the value for withdrawal_special_user.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal_special_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WithdrawalSpecialUser other = (WithdrawalSpecialUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getAutoBankRate() == null ? other.getAutoBankRate() == null : this.getAutoBankRate().equals(other.getAutoBankRate()))
                && (this.getToBankRate() == null ? other.getToBankRate() == null : this.getToBankRate().equals(other.getToBankRate()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal_special_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAutoBankRate() == null) ? 0 : getAutoBankRate().hashCode());
        result = prime * result + ((getToBankRate() == null) ? 0 : getToBankRate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdrawal_special_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userType=").append(userType);
        sb.append(", userId=").append(userId);
        sb.append(", autoBankRate=").append(autoBankRate);
        sb.append(", toBankRate=").append(toBankRate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}