package com.edaochina.shopping.api.dao.sys;

import com.edaochina.shopping.domain.entity.sys.BankCode;

import java.util.List;

public interface BankCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    int insert(BankCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    int insertSelective(BankCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    BankCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankCode record);

    List<BankCode> queryBankCodes();
}